name: Deploy Blazor to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET 9.0
        run: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash -s -- --version 9.0.0-rc.2 --install-dir ./dotnet
          echo "DOTNET_ROOT=$(pwd)/dotnet" >> $GITHUB_ENV
          echo "$(pwd)/dotnet" >> $GITHUB_PATH

      - name: Show dotnet version
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Blazor project
        run: dotnet publish --configuration Release --output build_output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_output/wwwroot
